export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const FILTER_CONTINENT = "FILTER_CONTINENT";
export const ORDER_COUNTRY = "ORDER_COUNTRY";
export const ORDER_POPULATION = "ORDER_POPULATION";
export const FILTER_COUNTRY = "FILTER_COUNTRY";
export const CREATE_ACTI = "CREATE_ACTIVI";
